sudo: false

language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'nightly'
  - 'pypy3'

env:
  - DJANGO_VERSION=master
  - DJANGO_VERSION=2.1.x
  - DJANGO_VERSION=2.0.x
  - DJANGO_VERSION=1.11.x

matrix:
  exclude:
    - python: '3.5'
      env: DJANGO_VERSION=master
    - python: '3.4'
      env: DJANGO_VERSION=master
    - python: '3.4'
      env: DJANGO_VERSION=2.1.x

install:
  - pip install tox coveralls

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - coveralls
